spring:
  jpa:
    open-in-view: false
  datasource:
    driverClassName: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  h2:
    console:
      enabled: true
      path: "/h2-console"
  sql:
    init:
      mode: always

springdoc:
  swagger-ui:
    url: /swagger.yml
  api-docs:
    enabled: true